// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhmiipdlmxlgyuilnogv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhobWlpcGRsbXhsZ3l1aWxub2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNDcwODMsImV4cCI6MjA2MTgyMzA4M30.JlSA4Yn1X2bCrWOGN2Zd30Lbi9iuwSt4bG5mn5P075o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);